name: build
description: "This action builds Quicksilver plugins."
inputs:
  CONFIGURATION:
    description: "Determines whether a Release or Debug configuration will be built"
    required: true
    default: Release

runs:
  using: "composite"
  env:
    QS_SOURCE_ROOT: /tmp/git/quicksilver
    CONFIGURATION: ${{ env.CONFIGURATION }}
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Clone QS to latest tag
      shell: bash
      run: |
        # Much quicker to only clone the latest tag as opposed to full clone and then check out tag
        latest_tag=$(
          git ls-remote --tags --refs --sort="-v:refname" https://github.com/quicksilver/quicksilver |
            awk -F/ '{ print $NF; exit }'
        )
        mkdir -p "${QS_SOURCE_ROOT}"
        git clone --recurse-submodules --branch="${latest_tag}" --depth=1 https://github.com/quicksilver/Quicksilver.git "${QS_SOURCE_ROOT}"
        git checkout "${latest_tag}"
    - name: Set plugin name
      shell: bash
      env:
      run: |
        PLUGIN_NAME=$(
          xcodebuild -showBuildSettings -json |
            jq -r 'map(.buildSettings.FULL_PRODUCT_NAME) | first'
        )
        echo "PLUGIN_NAME=${PLUGIN_NAME}" >> $GITHUB_ENV
    - name: build plugin
      run: /tmp/git/quicksilver/Quicksilver/Tools/build-plugin
    - name: Archive plugin
      shell: bash
      working-directory: /tmp/QS/build/Release/Quicksilver.app/Contents/PlugIns/
      run: |
        tar -czvf "${PLUGIN_NAME}.tar.gz" "${PLUGIN_NAME}"
    - name: Upload components for sign action
      uses: actions/upload-artifact@v4
      with:
        name: UNSIGNED_PLUGIN
        path: /tmp/QS/build/Release/Quicksilver.app/Contents/PlugIns/${{ env.PLUGIN_NAME }}.tar.gz
    - name: Download targz artifact
      uses: actions/download-artifact@v4
      with:
        name: UNSIGNED_PLUGIN
        path: /tmp/QS/build/Release/
    - name: Sign plugin
      shell: bash
      working-directory: /tmp/QS/build/Release/
      run: |
        cd /tmp/QS/build/Release
        tar -xzvf "${PLUGIN_NAME}.tar.gz"
        rm -- "${PLUGIN_NAME}.tar.gz"

        # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
        KEYCHAIN_PATH=${RUNNER_TEMP}/app-signing.keychain-db
        CERTIFICATE_PATH=${RUNNER_TEMP}/build_certificate.p12

        echo -n "${MACOS_CERTIFICATE}" |
          base64 --decode --output "${CERTIFICATE_PATH}"

        security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security default-keychain -s "${KEYCHAIN_PATH}"
        security set-keychain-settings -lut 21600 "${KEYCHAIN_PATH}"

        security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"

        security import "${CERTIFICATE_PATH}" -P "${MACOS_CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
        codesign --force -vvv --deep --sign "${SIGNING_IDENTITY}" "${PLUGIN_NAME}"
    - name: Archive signed plugin
      shell: bash
      working-directory: /tmp/QS/build/Release
      run: |
        tar -czvf "${PLUGIN_NAME}.tar.gz" "${PLUGIN_NAME}"
    - name: Upload document
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PLUGIN_NAME }}
        path: /tmp/QS/build/Release/${{ env.PLUGIN_NAME }}.tar.gz
    - name: Push to Production
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        set -x
        ls -l /tmp/git/quicksilver/Quicksilver/Tools/qs-push-plugin

        ./qs-push-plugin \
          --user "${{ secrets.QS_PUSH_PLUGIN_USER }}" \
          --password "${{ secrets.QS_PUSH_PLUGIN_PASS }}" \
          --changes "<ul><li>this is a test</li></ul>" \
          "/tmp/QS/build/Release/${{ env.PLUGIN_NAME }}.qsplugin"
